"""Render the README's lineage diagram from the REAL column graph.

Hand-drawn architecture diagrams drift from the code the moment either changes,
and nobody notices because a picture has no tests. This one is generated by
querying the actual graph whatbreaks builds for the quickstart example, so it
cannot claim a relationship the tool does not find.

It illustrates the distinction the whole project rests on: `dbt ls` answers at
model granularity, and one of the two consumers here is affected only through a
WHERE clause, which projection lineage alone would miss entirely.

    python tools/make_lineage_svg.py docs/assets/lineage.svg
"""

from __future__ import annotations

import sys
from pathlib import Path

from whatbreaks.analysis import Analysis
from whatbreaks.lineage.column_graph import ColumnRef

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "examples" / "quickstart" / "base" / "target" / "manifest.json"
CHANGED = ColumnRef("model.shop.stg_orders", "status")

BG = "#12141a"
PANEL = "#1b1e26"
FG = "#c9d1d9"
DIM = "#6e7681"
RED = "#f47067"
AMBER = "#d8a657"
LINE = "#30363d"

W, H = 860, 300
MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"


def esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def collect() -> tuple[list[str], list[tuple[str, str]], list[str]]:
    """-> (all downstream model names, (model, column) pairs, filter-only models)"""
    analysis = Analysis.run(BASE)
    graph = analysis.graph
    names = {uid: node.name for uid, node in analysis.manifest.models.items()}

    projected = [
        (names[e.downstream.node_id], e.downstream.column)
        for e in graph.downstream_of(CHANGED)
        if e.downstream.node_id in names
    ]
    filter_only = sorted(
        {
            names[r.downstream_model]
            for r in graph.required
            if r.upstream == CHANGED and r.downstream_model in names
        }
    )
    everything = sorted(
        {
            names[uid]
            for uid, node in analysis.manifest.models.items()
            if CHANGED.node_id in node.depends_on
        }
    )
    return everything, sorted(set(projected)), filter_only


def text(
    x: float,
    y: float,
    content: str,
    *,
    fill: str = FG,
    size: int = 13,
    weight: str = "normal",
    anchor: str = "start",
) -> str:
    return (
        f'<text x="{x:.0f}" y="{y:.0f}" fill="{fill}" font-family="{MONO}" '
        f'font-size="{size}" font-weight="{weight}" text-anchor="{anchor}">{esc(content)}</text>'
    )


def build() -> str:
    everything, projected, filter_only = collect()

    out: list[str] = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}" role="img" '
        f'aria-label="Model-level versus column-level blast radius">',
        f'<rect width="{W}" height="{H}" rx="10" fill="{BG}"/>',
    ]

    # ---- the change under review -------------------------------------
    out.append(text(28, 40, "change under review", fill=DIM, size=11))
    out.append(text(28, 64, "stg_orders.status  removed", fill=RED, size=14, weight="bold"))
    out.append(f'<line x1="28" y1="80" x2="{W - 28}" y2="80" stroke="{LINE}" stroke-width="1"/>')

    # ---- left panel: model granularity -------------------------------
    out.append(f'<rect x="28" y="102" width="380" height="164" rx="8" fill="{PANEL}"/>')
    out.append(text(48, 128, "dbt ls --select stg_orders+", fill=DIM, size=12))
    out.append(text(48, 152, "model granularity", fill=AMBER, size=11))
    y = 180
    for name in everything:
        out.append(text(48, y, f"* {name}", fill=FG))
        out.append(text(210, y, "affected?", fill=DIM, size=11))
        y += 24
    out.append(text(48, y + 6, "every model downstream, column or not", fill=DIM, size=11))

    # ---- right panel: column granularity -----------------------------
    out.append(f'<rect x="452" y="102" width="380" height="164" rx="8" fill="{PANEL}"/>')
    out.append(text(472, 128, "whatbreaks", fill=DIM, size=12))
    out.append(text(472, 152, "column granularity", fill=RED, size=11))
    y = 180
    for model, column in projected:
        out.append(text(472, y, f"* {model}.{column}", fill=FG))
        out.append(text(700, y, "selects it", fill=DIM, size=11))
        y += 24
    for model in filter_only:
        out.append(text(472, y, f"* {model}", fill=FG))
        out.append(text(700, y, "filters on it", fill=AMBER, size=11))
        y += 24
    out.append(text(472, y + 6, "exactly what touches the column", fill=DIM, size=11))

    # ---- the point ---------------------------------------------------
    out.append(
        text(
            W / 2,
            H - 18,
            "a filter-only dependency breaks the query without changing any column",
            fill=DIM,
            size=11,
            anchor="middle",
        )
    )
    out.append("</svg>")
    return "\n".join(out) + "\n"


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    destination = Path(args[0]) if args else ROOT / "docs/assets/lineage.svg"
    destination.parent.mkdir(parents=True, exist_ok=True)
    svg = build()

    if "--check" in sys.argv:
        if not destination.exists() or destination.read_text(encoding="utf-8") != svg:
            print(f"STALE  {destination.name} does not match the current graph")
            print("       regenerate with: python tools/make_lineage_svg.py")
            return 1
        print(f"OK     {destination.name} matches the current graph")
        return 0

    destination.write_text(svg, encoding="utf-8")
    print(f"wrote {destination.relative_to(ROOT)}  ({len(svg):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
